### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by TrincaMirko** [Capsize-Games/chatai#10]
So i create a new bug for the list of errors during installation(3).
Prerequisite:Python 3.10.6 in a new env and git the new version

i went all in and manually installed all the packages that it trowed at me to find the culprits (this is the list but i think i miss some)
pip install torch==1.13.1
pip install nvidia-tensorrt==8.4.3.1
pip install requests==2.28.2
pip install pyre-extensions==0.0.23
pip install requests-oauthlib==1.3.1
pip install safetensors==0.3.0
pip install PyQt6==6.4.2
pip install xformers==0.0.16
pip install aihandler==1.8.12
pip install bitsandbytes==0.37.0
pip install torchaudio==0.13.1
pip install pyqtdarktheme==2.1.0
pip install aihandler==1.8.12
pip install bitsandbytes==0.37.0
pip install torchaudio==0.13.1
pip install torchvision==0.14.1
pip install huggingface-hub==0.13.3
pip install bitsandbytes-cuda117==0.26.0.post2
pip install accelerate==0.18.0
pip install pyqtdarktheme==2.1.0
pip install opencv-python==4.7.0.72
pip install deepspeed==0.8.0
pip install setuptools==65.5.1
pip install scipy==1.10.1
pip install tokenizers==0.13.2
pip install nvidia-pyindex
pip install pytorch-lightning==2.0.
pip install aihandler==1.8.12
pip install numpy==1.23.5
pip install deepspeed==0.8.0
pip install tensorflow==2.12.0

After that the errors remainings are:
---1---
ERROR: Could not find a version that satisfies the requirement triton==2.0.0.dev20221202 (from aihandler) (from versions: none)
ERROR: No matching distribution found for triton==2.0.0.dev20221202

---2---
ERROR: Could not find a version that satisfies the requirement nvidia-tensorrt==8.4.3.1 (from aihandler) (from versions: 0.0.1.dev4, 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-tensorrt==8.4.3.1

---3--- (the same as before)
Collecting deepspeed==0.8.0
  Downloading deepspeed-0.8.0.tar.gz (749 kB)
     ---------------------------------------- 749.9/749.9 kB 9.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Trinca\AppData\Local\Temp\pip-install-mdg72xkd\deepspeed_c397623b64204035987b9cbfb9137476\setup.py", line 156, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\Trinca\AppData\Local\Temp\pip-install-mdg72xkd\deepspeed_c397623b64204035987b9cbfb9137476\setup.py", line 48, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
      ←[93m [WARNING] ←[0m async_io requires the dev libaio .so object and headers but these were not found.
      ←[93m [WARNING] ←[0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
      ←[93m [WARNING] ←[0m One can disable async_io with DS_BUILD_AIO=0
      ←[31m [ERROR] ←[0m Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by w4ffl35** [comment]
It seems like you're working with an older vapersion onpf chatai.

Please see the installation spinstructions for aihandler under windows:

https://github.com/Capsize-Games/aihandler

Also see list of requirements here:

https://github.com/Capsize-Games/aihandler/blob/master/setup.py

**Comment by w4ffl35** [comment]
Are you trying to install on WSL?

**Comment by TrincaMirko** [comment]
ok managed to install all the prerequisite now i'm facing a  

File "L:\AI\chatai\env\lib\site-packages\aihandler\runner.py", line 14, in <module>
from controlnet_aux import HEDdetector, MLSDdetector, OpenposeDetector
ModuleNotFoundError: No module named 'controlnet_aux'

Btw installing without WSL (for the triton i managed a sketchy whl that was around. if needed i can provide it)

**Comment by w4ffl35** [comment]
if you have the source of the wheel i'd be interested in taking a look but i don't want to distribute unknown sources

can you check that controlnet_aux is installed? `pip -m` and look for control_net - you should have version 0.0.1 - I would have expected it to install - its in the requirements right here https://github.com/Capsize-Games/aihandler/blob/master/setup.py#L9

**Comment by w4ffl35** [comment]
I'm closing this issue for now - be sure respond here if you have more details. also feel free to join the discord
