### ISSUE TITLE
itch.io chat-ai page has a reference to stable diffusion

### ISSUE THREAD

**Issue by kajuberdut** [Capsize-Games/chatai#25]
Sorry for noting this here, I don't want to make an itch.io account.

I was reading through the page at https://capsizegames.itch.io/chat-ai and noticed that there is a footnote about stable diffusion that looks like copy pasta from another readme.

![image](https://user-images.githubusercontent.com/8014746/229323522-fa36dbed-c2e3-4a07-8270-50049893e423.png)

I think that the ** footnote is probably in error and should be erased and the *** footnote should be changed to **.

**Comment by kajuberdut** [comment]
Or possibly the words "stable diffusion models" should just be changed to "Google Flan-T5 models"

**Comment by w4ffl35** [comment]
thanks
