### ISSUE TITLE
deepspeed error on windows

### ISSUE THREAD

**Issue by TrincaMirko** [Capsize-Games/chatai#5]
When installing from windows it gave this error deepspeed==0.8.0

 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Trinca\AppData\Local\Temp\pip-install-x3yegzxd\deepspeed_455d1e6923c14e0789b485515a37a937\setup.py", line 156, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\Trinca\AppData\Local\Temp\pip-install-x3yegzxd\deepspeed_455d1e6923c14e0789b485515a37a937\setup.py", line 48, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      DS_BUILD_OPS=1
      ←[93m [WARNING] ←[0m async_io requires the dev libaio .so object and headers but these were not found.
      ←[93m [WARNING] ←[0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
      ←[93m [WARNING] ←[0m One can disable async_io with DS_BUILD_AIO=0
      ←[31m [ERROR] ←[0m Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

The problems with deepspeed seems recurring on windows and they are still opened right now. I think i will try it on the ubuntu vm

**Comment by w4ffl35** [comment]
Thanks for the report. This should be fixed in [v1.0.6](https://github.com/Capsize-Games/chatai/releases/tag/v1.0.6).

[See updated installation instructions here](https://github.com/Capsize-Games/chatai#development)
